# Created by: archinstall
# Created on: 2026-03-05_17-19-46
title   Arch Linux (linux)
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options cryptdevice=UUID=19e32dec-c827-4b57-9fb0-4f427a6e483f:cryptlvm root=/dev/ArchinstallVg/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs amd_pmc.enable_stb=1
